version: "3.3"
services:
  api:
    image: ghcr.io/0x77dev/streamity/api:latest
    environment:
      - DATABASE_URL="postgres://postgres:password@postgres:5432/postgres"
      - ELASTCISEARCH_URL="http://elasticsearch:9200"
      - NATS_URL="nats://nats:4222"
    ports:
      - 3000:3000

  stream:
    depends_on:
      - api
    environment:
      - NATS_URL="nats://nats:4222"
    image: ghcr.io/0x77dev/streamity/stream:latest
    ports:
      - 1025:1025

  recognition:
    environment:
      - NATS_URL="nats://nats:4222"
    image: ghcr.io/0x77dev/streamity/recognition:latest
    # runtime: nvidia

  nats:
    image: nats:latest
    restart: unless-stopped
    ports:
      - 4222:4222
      - 8222:8222
    logging:
      options:
        max-file: "5"
        max-size: "1m"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    logging:
      options:
        max-file: "5"
        max-size: "1m"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  postgres-data: null
  redis-data: null
  elasticsearch-data: null
